on: [push, pull_request]

name: CI

env:
  CARGO_INCREMENTAL: 0

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - "1.61"
    steps:
      - name: Install development libraries
        run: sudo apt update && sudo apt install libasound2-dev -y

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        run: rustup toolchain add ${{ matrix.rust }}

      - name: Downgrade winnow to MSRV
        if: ${{ matrix.rust }} == "1.61"
        run: cargo update -p winnow --precise 0.4.1

      - name: cargo test
        run: cargo test

      - name: cargo test --all-features
        run: cargo +${{ matrix.rust }} test --all-features

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: cargo fmt -- --check
        run: cargo fmt -- --check
